port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

proxies:
  - name: "MySocks5Proxy"
    type: socks5
    server: 185.4.182.66
    port: 24267
    username: modeler_WDw8gp
    password: kBRHQBgf7frC

proxy-groups:
  - name: "ProxyGroup"
    type: select
    proxies:
      - "MySocks5Proxy"

rules:
  - RULE-SET,https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-clashx.lst,ProxyGroup
  - MATCH,DIRECT
